import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import ScrollUp from "@/components/scroll-up";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Quran",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <section className="container">
          <Header />
          {children}
          <ScrollUp />
        </section>
      </body>
    </html>
  );
}
